Parallelise mutation tests (#2395)
- Run each mutation test project in parallel in its own GitHub Actions job.
- Install the .NET 8 SDK when required now we only explicitly install .NET 6 and 9.
- Minimise redundant work when running mutation tests.

diff --git a/.github/workflows/mutation-tests.yml b/.github/workflows/mutation-tests.yml
--- a/.github/workflows/mutation-tests.yml
+++ b/.github/workflows/mutation-tests.yml
@@ -31,8 +31,14 @@ jobs:
         include:
           - name: core
             target: Core
+          - name: extensions
+            target: Extensions
           - name: legacy
             target: Legacy
+          - name: ratelimiting
+            target: RateLimiting
+          - name: testing
+            target: Testing
 
     steps:
 
@@ -46,26 +52,37 @@ jobs:
       with:
         dotnet-version: |
           6.0.x
+          8.0.x
 
     - name: Setup .NET SDK
       uses: actions/setup-dotnet@87b7050bc53ea08284295505d98d2aa94301e852 # v4.2.0
 
-    - name: Setup NuGet cache
-      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
-      with:
-        path: ~/.nuget/packages
-        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props') }}
-        restore-keys: ${{ runner.os }}-nuget-
-
-    - name: Run mutation tests
+    - name: Run mutation tests for ${{ matrix.target }}
       shell: pwsh
       env:
-        MUTATION_TARGET: 'Mutation${{ matrix.target }}'
+        MUTATION_TARGET: 'MutationTests${{ matrix.target }}'
+        SKIP_POLLY_ANALYZERS: 'true'
       run: ./build.ps1 -Target ${env:MUTATION_TARGET}
 
     - name: Upload Mutation Report
-      if: always()
+      if: ${{ !cancelled() }}
       uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
       with:
         name: mutation-report-${{ matrix.name }}
         path: ./artifacts/mutation-report
+
+  mutation-tests:
+    needs: [ mutations ]
+    if: ${{ always() }}
+    runs-on: ubuntu-latest
+    env:
+      MUTATIONS_SUCCESS: ${{ !contains(needs.*.result, 'failure') }}
+    steps:
+      - run: |
+          if [ "$MUTATIONS_SUCCESS" == "true" ]
+          then
+            echo 'Mutation tests successful ✅'
+          else
+            echo 'One or more mutation test runs failed ❌'
+            exit 1
+          fi
